### ISSUE TITLE
Paper: Deep Mutual Learning

### ISSUE THREAD

**Issue by NeelayS** [SforAiDl/KD_Lib#49]
* Paper Link: https://arxiv.org/abs/1706.00384

### Description
```
Rather than one way transfer between a teacher and a student, an ensemble of students learn collaboratively and teach each other throughout the training process
```

**Comment by NeelayS** [comment]
This paper uses multiple students with different initial weights. However, to preserve our API, I was thinking of taking one student, making copies of it and adding Gaussian noise to the weights of the copies. 
That should have have the same effect right ? @Het-Shah

**Comment by Het-Shah** [comment]
Yea to preserve the current API you can add a term in the `__init__` as well for the number of students you would want, and then take the approach as you said. Or you can make a list of students instead of one student (this will give freedom of architecture as well like different architectures for the students).

**Comment by NeelayS** [comment]
Hmmm. The second option seems better. But then we''ll have to take in a list of optimizers as well. Wouldn't that be a bit messy ?

**Comment by Het-Shah** [comment]
We already are doing such an implementation right? The TAKD one has this sort of approach afaik.
